# Generated by Django 4.2.7 on 2025-07-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("store_id", models.IntegerField()),
                ("current_stock", models.PositiveIntegerField()),
                ("weekly_sales_rate", models.FloatField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_dead_stock", models.BooleanField(default=False)),
            ],
        ),
    ]
