# Generated by Django 4.2.7 on 2025-07-12 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_transferrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.product",
            ),
        ),
    ]
